### ISSUE TITLE
Dist file

### ISSUE THREAD

**Issue by enricofer** [gamestdio/three-text2d#10]
The library seems to be great! But could you please provide last release distribution file? 
not found at https://unpkg.com/three-text2d@0.3.0/dist

**Comment by voondo** [comment]
Or maybe some instructions about how to build them.
```
npm install
npm run prepublish
```
doesn't work here

**Comment by endel** [comment]
Hi there, thanks for your feedback.

Since issue #5 has been solved we've decided to remove the dist snapshot in favor of including this project as a node module. 

I need to investigate how to generate the dist file while still being able to use it as a module.

In case you need you can grab the last build version from the history here: https://github.com/gamestdio/three-text2d/blob/bd7e577597e2861b8b4641d91d56089b5b135468/dist/three-text2d.js

**Comment by endel** [comment]
Hey @enricofer @voondo ,

Just fixed the dist generation using webpack's `external` configuration: https://github.com/gamestdio/three-text2d/blob/master/webpack.dist.config.js#L23-L25

Please let me know if it works for you. If you're upgrading from v0.2.0 to v0.3.0 please head up to the [changelog](https://github.com/gamestdio/three-text2d/blob/master/CHANGELOG.md)

Cheers!

**Comment by enricofer** [comment]
You are very kind and quinck! Thank you! I will soon check it out !

**Comment by voondo** [comment]
thanks a lot !
