### ISSUE TITLE
Uncaught ReferenceError: THREE is not defined

### ISSUE THREAD

**Issue by pjanik** [gamestdio/three-text2d#5]
...when I try to import this package using webpack.

I can see that there's an assumption that THREE is globally available. 
Wouldn't be possible to use require('three') and add it as peerDependency?

**Comment by gpolyn** [comment]
@pjanik, you may already have a workaround, but here follows mine, in configuration.
```
const webpack = require('webpack');

var plugins = [
     new webpack.ProvidePlugin({
       THREE: "three"
         })
   ]

module.exports = {
  ...
  plugins: plugins
}
```

**Comment by endel** [comment]
Thanks for the workaround @gpolyn. It would be great to support webpack without having to expose THREE globally though. 

Do you guys know if there's a way to use `peerDependency` and be able to generate a standalone build file, without a pre-built THREE version on it? [Like this](https://github.com/gamestdio/three-text2d/blob/master/dist/three-text2d.js).

Cheers!

**Comment by gpolyn** [comment]
@endel, I'm still a webpack novice, so I don't know. Looks like `peerDependency` may be deprecated in favor of loader? Will look into it.

**Comment by FunkMonkey** [comment]
I second pjanik's request to simply use `const THREE = require('three');` (or something similar) wherever it is needed.

Webpack can handle the rest itself, like it handles every other npm library. `peerDependencies` don't have much to do with webpack itself. They are not deprecated in the npm world (though they slightly changed with npm 3). You should probably add `three` as a `peerDependency`, though you should do that anyway despite of the changes we're proposing. 

I for one, use [electron](https://github.com/electron/electron) in my current project, which is why your workaround is not working for me.

**Comment by endel** [comment]
@FunkMonkey could you use `three-text2d` in your project?

**Comment by endel** [comment]
I've published `v0.2.3-rc1` with the `peerDependencies`. The only reason I was hesitant of doing it is because the file [`dist/three-text2d`](https://github.com/gamestdio/three-text2d/blob/master/dist/three-text2d.js) generated through browserify will now include THREE by default. 

Do you mind checking if it works in your environment @FunkMonkey ?
Cheers!

**Comment by FunkMonkey** [comment]
Thank you very much! I'll try and check it out next week. But looking at the commit, it should work.

But may I ask why you are using `browserify` in this module? Shouldn't `browserify` (or `webpack` for that matter) rather be used in the "parent" project that uses `three-text2d`? Or is it just for your example in the `index.html`?

**Comment by endel** [comment]
@FunkMonkey thanks! Yes, it's for the example an also to people who wants to grab the library script in the old-fashion way. Maybe it doesn't make sense to support this sort of thing anymore, right?

**Comment by FunkMonkey** [comment]
@endel I don't think it is necessary anymore, but who knows. You could package an example zip and provide it as a download on github and leave it out of the repository. 

Concerning browserify including THREE by default: both browserify and webpack support externals ([here](http://benclinkinbeard.com/posts/external-bundles-for-faster-browserify-builds/) and [here](https://webpack.github.io/docs/configuration.html#externals))

**Comment by endel** [comment]
Thanks for the feedback everyone! I'll close this since it seems to be fine now. Version 0.3.0 has been released with a slight breaking change. Have a look at the [changelog](https://github.com/gamestdio/three-text2d/blob/master/CHANGELOG.md). Cheers!
